name: Personal 6
createdAt: '2026-02-10T14:35:10Z'
projects:
- name: Project 1
  path: project-1
github:
  owner: jlong
  name: personal-docs-space
  cloneURL: https://github.com/jlong/personal-docs-space.git
